export const CREATE_PRONUNCIATION = "CREATE_PRONUNCIATION";
export const RETRIEVE_PRONUNCIATIONS = "RETRIEVE_PRONUNCIATIONS";
export const UPDATE_PRONUNCIATION = "UPDATE_PRONUNCIATION";
export const DELETE_PRONUNCIATION = "DELETE_PRONUNCIATION";
export const DELETE_ALL_PRONUNCIATIONS = "DELETE_ALL_PRONUNCIATIONS";